services:  # Defines the services that make up your application.

  api-notes:  # Configuration for the web service.
    container_name: api-notes
    build: ./
    command: ./start_notes_api.sh --environment=local
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
      - ./.env.secrets
    depends_on:
      - db-notes
      - redis-notes
    networks:
      - notes_api_network

  db-notes:  # Configuration for the database service.
    container_name: db-notes
    image: postgis/postgis:13-3.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      - ./.env.secrets
    networks:
      - notes_api_network

  redis-notes:  # Configuration for the Redis service.
    container_name: redis-notes
    image: "redis:7.2.1"
    env_file:
      - ./.env
      - ./.env.secrets
    command: redis-server --requirepass ${REDIS_PASSWORD-8666989}
    networks:
      - notes_api_network

volumes: # Defines named volumes for persistent storage.
  postgres_data:  # Defines a named volume for PostgresSQL data storage.

networks:
  notes_api_network:
    driver: bridge