services:
  api-notes:
    image: molero3111/notes-api:latest
    container_name: api-notes
    pull_policy: always
    restart: always
    command: ["./wait-for-it.sh", "db-notes:5432", "--", "./start_notes_api.sh"]
    expose:
      - 8000
    ports:
      - "${HOST_MACHINE_WEB_PORT:-8000}:8000"
    env_file:
      - ./.env
      - ./.env.secrets
    depends_on:
      - db-notes
      - redis-notes
    networks:
      - notes_api_staging_network

  db-notes:
    image: postgis/postgis:13-3.1
    container_name: db-notes
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      - ./.env.secrets
    networks:
      - notes_api_staging_network

  redis-notes:
    image: "redis:7.2.1"
    container_name: redis-notes
    restart: always
    env_file:
      - ./.env
      - ./.env.secrets
    command: redis-server --requirepass ${REDIS_PASSWORD-8878759}
    networks:
      - notes_api_staging_network

volumes:
  postgres_data:

networks:
  notes_api_staging_network:
    driver: bridge
