version: '3.8'

services:
  notes-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: ./start_notes_api.sh
    expose:
      - 8000
    ports:
      - "${HOST_MACHINE_WEB_PORT:-8000}:8000"  # Map port from host machine or default to 8000
    env_file:
      - ./.env
      - ./.env.secrets
    depends_on:
      - notes-db
      - notes-redis
    networks:
      - notes_api_staging_network

  notes-db:
    image: postgis/postgis:13-3.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      - ./.env.secrets
    networks:
      - notes_api_staging_network

  notes-redis:
    image: "redis:7.2.1"
    restart: always
    env_file:
      - ./.env
      - ./.env.secrets
    command: redis-server --requirepass ${REDIS_PASSWORD-8878759}
    networks:
      - notes_api_staging_network

volumes:
  postgres_data:

networks:
  notes_api_staging_network:
    external: true
