version: '3.8'

networks:
  notes_manager_staging_network:
    external: true

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: ./start_notes_api.sh
    env_file:
      - ./.env
    expose:
      - 8000
    networks:
      - notes_manager_staging_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./nginx/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443  # Expose port 443 for SSL
    networks:
      - notes_manager_staging_network
