version: '3.8'  # Specifies the version of the Docker Compose file format being used.

services:  # Defines the services that make up your application.

  web:  # Configuration for the web service.
    build: ./  # Specifies the location of the Dockerfile to build the container.
    command: ./start_notes_api.sh --environment=local
    volumes:  # Mounts volumes from the host machine to the container.
      - .:/app  # Maps the current directory on the host to /app directory in the container.
    ports:  # Exposes ports from the container to the host.
      - 8000:8000  # Maps port 8000 on the host to port 8000 in the container.
    env_file:  # Specifies the environment file to use.
      - ./.env  # Reads environment variables from the .env file.
    networks:  # Specifies the networks the service should be connected to.
      - notes_manager_network  # Connects this service to the "notes_manager_network" network.

networks:  # Defines Docker networks.
  notes_manager_network:  # Configuration for the "notes_manager_network" network.
    external: true  # Indicates that this network is defined externally and should be reused if it already exists.