apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-redis-deployment
  labels:
    deployment: notes-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: notes-redis
  template:
    metadata:
      labels:
        pod: notes-redis
    spec:
      containers:
        - name: notes-redis-container
          image: redis:7.2.1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: REDIS_PASSWORD
          command: [ "redis-server", "--requirepass", "$(REDIS_PASSWORD)" ]  # Set the Redis password