apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-media-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: notes-media-pv
