apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-postgres-container
  template:
    metadata:
      labels:
        app: notes-postgres-container
        tier: backend
    spec:
      containers:
        - name: notes-postgres-container
          image: postgis/postgis:13-3.1
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: notes-postgres-pvc